version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing dependencies
      - ./gradlew dependencies
  build:
    commands:
      - echo Building the JAR
      - ./gradlew build
artifacts:
  files:
    - build/libs/*.jar
  discard-paths: yes
  base-directory: build/libs
