AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ExistingRoleName:
    Type: String
    Description: "The name of the existing IAM role to use for the instance profile."

Resources:
  # IAM Instance Profile for EC2 (using existing role)
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - Ref: ExistingRoleName  # Reference to the existing IAM role passed as a parameter

  # EC2 Instance
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-04a81a99f5ec58529 # Replace with your AMI ID
      KeyName: developer_keypair  # Replace with your key pair name
      IamInstanceProfile: !Ref InstanceProfile
      Tags:
        - Key: Project
          Value: Demo

# Outputs section to provide the instance ID and instance profile
Outputs:
  InstanceId:
    Description: "The Instance ID of the EC2 instance"
    Value: !Ref MyEC2Instance

  InstanceProfileArn:
    Description: "The ARN of the IAM instance profile"
    Value: !GetAtt InstanceProfile.Arn
